[Node]
DataDir = "node/validator1"
HTTPHost = "127.0.0.1"
HTTPPort = 8545
HTTPModules = ["eth","net","web3","txpool"]
WSPort = 8546
WSModules = ["eth","net","web3","txpool"]
IPCPath = "geth.ipc"
NoUSB = true

[P2P]
ListenAddr = ":30303"
MaxPeers = 50
NoDiscovery = false

[Miner]
Etherbase = ""   # скрипт подставит адрес
